site_name: DragonFly BSD documentation (BETA)
site_url: https://docs.dragonflybsd.org

repo_name: DragonFlyBSD/docs.dragonflybsd.org
repo_url: https://github.com/DragonFlyBSD/docs.dragonflybsd.org

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DragonFlyBSD
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dragonflybsd

nav:
  - Home: index.md
  - Getting started:
    - Introduction: user-guide/intro.md
    - Downloading: user-guide/download.md
    - Installation: user-guide/install.md
    - Configuration: user-guide/config.md
  - Next steps:
    - Installing software: user-guide/install-software.md
  - More documentation:
    - Manual pages: man-pages.md
  - About: about.md

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
